# -*- coding: utf-8 -*-
"""DJ_RADYO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1goCUE04eW017fQ2w3b7beRAwPCrPZBO_
"""

!pip install gradio transformers

import random
import gradio as gr
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from google.colab import drive
import torch


# === DRIVE BAĞLANTISI ===
drive.mount('/content/drive')

# === DJ MODELİNİ YÜKLE ===
dj_model_path = "/content/drive/MyDrive/dj_model_flan_t51"
tokenizer = AutoTokenizer.from_pretrained(dj_model_path, local_files_only=True)
model = AutoModelForSeq2SeqLM.from_pretrained(dj_model_path, local_files_only=True)

# === DUYGU VERİLERİ ===
duygu_etiketleri = [
    "hüzünlü", "mutlu", "aşık", "sinirli", "enerjik", "yalnız",
    "nostaljik", "yorgun", "motive", "saygılı", "kaygılı"
]

renk_ve_anlam = {
    "hüzünlü": ("mavi", "#4A90E2"),
    "mutlu": ("turkuaz", "#30E3CA"),
    "aşık": ("kırmızı", "#FF3B3F"),
    "sinirli": ("mor", "#8E44AD"),
    "enerjik": ("sarı", "#F1C40F"),
    "yalnız": ("siyah", "#1C1C1C"),
    "nostaljik": ("kahverengi", "#A0522D"),
    "yorgun": ("beyaz", "#FFFFFF"),
    "motive": ("turuncu", "#FFA500"),
    "kaygılı": ("yeşil", "#6B8E23"),
    "saygılı": ("lacivert", "#1F3A93")
}

renk_anlamlari = {
    "sarı": "Geçiciliği ve dikkati simgeler.",
    "mavi": "Sakinlik ve huzur anlamına gelir.",
    "siyah": "Güç, hırs ve yas anlamı taşır.",
    "kahverengi": "Samimiyet ve hareketliliği ifade eder.",
    "turuncu": "Enerji, mutluluk ve coşkuyu yansıtır.",
    "beyaz": "Saflık ve masumiyeti simgeler.",
    "kırmızı": "Tutku, sıcaklık ve gücü ifade eder.",
    "mor": "Asalet ve zenginliği temsil eder.",
    "yeşil": "Umut, güven ve huzur anlamına gelir.",
    "lacivert": "Otorite ve güven hissi verir.",
    "turkuaz": "Mutluluk ve canlılığı temsil eder."
}

# === MOD KALIPLARI ===
mod_kaliplar = [
    "Bugün hislerine bakılırsa modun sanırım",
    "Sanırım şu anda modun",
    "Duygularına göre modun",
    "Tahminime göre bugün senin modun",
    "Hissediyorum ki bugün modun",
    "Bana göre bugün tam olarak modun",
    "Ruh halin bence",
    "Galiba modun şu anda",
    "Bu satırların alt metni",
    "Şu anki enerjin bana"
]

# === ANONS BAŞLANGIÇ VE BİTİŞ KALIPLARI ===
basliklar = [
    "🎙️ DJ kabininden tüm frekanslara selam! Ruhunla aynı tondayız.",
    "📻 94.5 DJ Radyo’da duyguların ses bulduğu yerdeyiz.",
    "🎧 Kalbinin frekansını yakaladık... Şimdi DJ zamanı!",
    "🎵 İçindeki notalara dokunan bir yolculuk başlıyor!",
    "🌀 Hislerinin ritmini yakaladık, sıradaki parça sana özel!",
    "🌙 Geceye eşlik eden tınılarla sessizliği müziğe çeviriyoruz.",
    "🔥 Ruh halin bu yayında sese dönüştü! DJ Radyo’da bir başka gecedeyiz.",
    "✨ Hissetmeye cesaret et! Ritimle başlayan bir yolculuk başlıyor.",
    "💿 Kalbinin attığı ritimdeyiz... Sıradaki parça senin yansıman.",
    "🎚️ DJ mikserde, sen duygularında... Şimdi sesin tam ortasındayız!"
]

bitisler = [
    "🎶 Şimdi radyonun sesini biraz daha aç, çünkü bu daha başlangıç!",
    "🔊 Sakın ayrılma! Bu ritim gece boyu seninle olacak.",
    "📡 DJ Radyo yayında kal, çünkü frekanslar seni anlatıyor.",
    "✨ Bu sadece bir giriş... Ruhunun hikayesi müzikle devam ediyor!",
    "🎼 Sıradaki parça hislerini serbest bırakacak... Hazır ol!",
    "🌟 Ruhunu notalara bırak, DJ Radyo hep seninle.",
    "🎧 Ritim yükseliyor! DJ’le kal, tempo seninle yarışsın.",
    "🪐 Duygularına özel frekanslardayız... Tekrar buluşmak üzere!",
    "📀 Kulaklık sende, kontrol bizde... Müziğin kalbinde görüşürüz!",
    "🎤 Mikrofondan kalbine uzanan bir yolculuğa daha az sonra devam!"
]

# === ŞARKI VERİTABANI ===

sarki_veritabani = {

    "hüzünlü": [
        ("Ahmet Kaya - Kum Gibi", "https://open.spotify.com/track/5sNESr6pQfIhL3krM8CtZn"),
        ("Sezen Aksu - Gülümse", "https://open.spotify.com/track/3dWLnU94Yf5EX6w54N0vft"),
        ("Cem Adrian - Yalnızlık", "https://open.spotify.com/track/4uYzxd0W7UOHkMo7G5fK9o"),
        ("Manuş Baba - Eteği Belinde", "https://open.spotify.com/track/6Rwl8VWBYkcKU8aD0vWYRB"),
        ("Teoman - Kupa Kızı ve Sinek Valesi", "https://open.spotify.com/track/7s5L2HQI9iYjA2Jssm9Rre"),
        ("Feridun Düzağaç - Lavinya", "https://open.spotify.com/track/0XpdGFGcV48qN3oUNrWiTT"),
        ("Fikri Karayel - Yol", "https://open.spotify.com/track/0NaidDHuhrUlaKFLfp0XUi"),
        ("Melike Şahin - Sevmek Suçsa Suçluyum", "https://open.spotify.com/track/0BAI3tbiBNu8ZQZUZhfw7A"),
        ("Mabel Matiz - A Canım", "https://open.spotify.com/track/0oJY8cps2Z71N9w0yLmQgf"),
        ("Gripin - Durma Yağmur Durma", "https://open.spotify.com/track/4q3U8Mum6wl1Z2VjXivvTk")
    ],
    "mutlu": [
        ("Tarkan - Şımarık", "https://open.spotify.com/track/2WzWqVs2Yh0ZTfPikYpWIZ"),
        ("Kenan Doğulu - Çakkıdı", "https://open.spotify.com/track/1o5RtFKEJH1tU3cyZKXjCx"),
        ("Nil Karaibrahimgil - Ben Buraya Çıplak Geldim", "https://open.spotify.com/track/0cHRN4O1s3mt0IOLiTJpG0"),
        ("Athena - Arsız Gönül", "https://open.spotify.com/track/7IP5Fq3F09iLgCP6reUrVR"),
        ("MFÖ - Ele Güne Karşı", "https://open.spotify.com/track/0smAAirKoLoehnVYBo2L7m"),
        ("Kiss - I Was Made For Lovin' You ", "https://open.spotify.com/intl-tr/track/07q0QVgO56EorrSGHC48y3?si=f65426af566547a5"),
        ("Mor ve Ötesi - Bir Derdim Var", "https://open.spotify.com/track/6IdCHwfh5kbE3cKmFqCSx5"),
        ("Hande Yener - Kırmızı", "https://open.spotify.com/track/6RX5iFmyQjRpgO1xGJ5L9T"),
        ("Ajda Pekkan - Yakar Geçerim", "https://open.spotify.com/track/4vq2SvLKHHM1bCNiTf9yFr"),
        ("Göksel - Depresyondayım", "https://open.spotify.com/track/4NHmNIFezcyV7nFeKZCMRH"),
        ("Athena - Senden, Benden, Bizden", "https://open.spotify.com/track/2pYHyEVRuMdn4ImLaBPKY5")
    ],
    "aşık": [
        ("Yalın - Bir Bakmışsın", "https://open.spotify.com/track/5a9bV2xC6Ab7Rk8NV7OfIP"),
        ("Emre Aydın - Belki Bir Gün Özlersin", "https://open.spotify.com/track/3uA5LnZ4nLwF2rVRUMi30a"),
        ("Tuna Kiremitçi - Bu Aşk Burada Biter", "https://open.spotify.com/track/0Zq04yAFYJr7rkOhmDZKDr"),
        ("Kalben - Sadece", "https://open.spotify.com/track/4Z9Drs6dp0QF1G13wLChPw"),
        ("Mabel Matiz - Gök Nerede", "https://open.spotify.com/track/6NnOgo2vNnMk8cJmo7r3Mw"),
        ("Edis - Martılar", "https://open.spotify.com/track/63g9ucLfjz2YKMzpxLysJ9"),
        ("Sıla - Yan Benimle", "https://open.spotify.com/track/4NVoaVJoPZo3JOGK9VmYnc"),
        ("Nilüfer - Son Perde", "https://open.spotify.com/track/0B1LFqOn2bbAOKWYIoFHZj"),
        ("Fenerbahçeliler - Lacivert Olmadan Sarı Sevilmez ", "https://open.spotify.com/intl-tr/track/5m0XSgInSBejkOyO4Fk59u?si=cc2e2dd6d7f54686"),
        ("Sertab Erener - Açık Adres", "https://open.spotify.com/track/0dL2BDkxl5z6zM6tMKLbDr"),
        ("Duman - Elleri Ellerime", "https://open.spotify.com/track/4u6EQz7w5CWwbHu4rhIuXy")
    ],
    "sinirli": [
        ("maNga - Beni Benimle Bırak", "https://open.spotify.com/track/5jyiF1DeNVzP5PBcLMxyZ2"),
        ("Mor ve Ötesi - Cambaz", "https://open.spotify.com/track/7pTnXzy3zzmtBOOvIczm4d"),
        ("Hayko Cepkin - Melekler", "https://open.spotify.com/track/1CCayHgCFFxPBwGzltChfG"),
        ("Duman - Belki Alışman Lazım", "https://open.spotify.com/track/4U3A7PQbx1qR5uNHQJsb2T"),
        ("Athena - Serseri Mayın", "https://open.spotify.com/track/0ObQ2dMw1yizn45RlGZKj3"),
        ("Şebnem Ferah - Mayın Tarlası", "https://open.spotify.com/track/4vAaQww8xMDn2mEZU7o1e6"),
        ("Kurban - Yosma", "https://open.spotify.com/track/3NKJjRYGLmNkoUZVnpR1wb"),
        ("Pentagram - Lions In A Cage", "https://open.spotify.com/track/2HTEjrPBHhzRMz8l4TBAg7"),
        ("Redd - Nefes Bile Almadan", "https://open.spotify.com/track/3D5LqZYptmFVW0Qd7xwbgN"),
        ("Cem Adrian - Sen Gel Diyorsun", "https://open.spotify.com/track/0GT0D54Ndiwwj0gEBE1a5Y")
    ],
    "enerjik": [
        ("Hadise - Düm Tek Tek", "https://open.spotify.com/track/3CJ74wGJb1ErfhCe9xH1kM"),
        ("Tarkan - Kuzu Kuzu", "https://open.spotify.com/track/4S7hnAp0uohRSMd4TrbSFL"),
        ("Gülşen - Bangır Bangır", "https://open.spotify.com/track/6zbmY9UKiWHD91aPPvp9hz"),
        ("Aleyna Tilki - Sen Olsan Bari", "https://open.spotify.com/track/0M2JbYkZB5WrrvhzraO5cT"),
        ("Edis - Dudak", "https://open.spotify.com/track/4C0WRYvciVXN7oL6gDJswV"),
        ("Demet Akalın - Nazar", "https://open.spotify.com/track/4gbRWljOtDLZOVWJk1K3Yo"),
        ("Simge - Yankı", "https://open.spotify.com/track/1rVcdVxapxOhyDf7S7phb2"),
        ("Ziynet Sali - Bana da Söyle", "https://open.spotify.com/track/1ugA1nP39TiMnTTe64N7NY"),
        ("Ajda Pekkan - Ajda 1990", "https://open.spotify.com/track/5oLKMnpyXjJvOE1phGMZCz"),
        ("Sertab Erener - Rengarenk", "https://open.spotify.com/track/6NkxOSSh7nRlyDdVcz0b96"),
        ("Yaşar - Kumralım", "https://open.spotify.com/intl-tr/track/3tCCD2qQLdC99YkRwGPSsx?si=dedf8318d62a4ddf")
    ],
    "yalnız": [
        ("Cem Adrian - Yalnızlık Senden Daha Çok Seviyor Beni", "https://open.spotify.com/track/6pPhQ6AStRt8s2VG0imU2F"),
        ("Manuş Baba - Ben Sana Vurgunum", "https://open.spotify.com/track/2XvHyqMkhqvJzjU4Ox5D7E"),
        ("Gripin - Yalnızlığın Çaresini Bulmuşlar", "https://open.spotify.com/track/6rIu5MbOeaqgWMSbXHE1x6"),
        ("Teoman - Renkli Rü yalar Oteli", "https://open.spotify.com/track/2S9lOTUUfNRnBeB0Te6rxg"),
        ("Berkay - Ayrılmam", "https://open.spotify.com/track/7rA6vIE9XWbyV6tk3MRVTh"),
        ("Kalben - Sadece", "https://open.spotify.com/track/4Z9Drs6dp0QF1G13wLChPw"),
        ("Candan Erçetin - Yalan", "https://open.spotify.com/track/4VjBd2HodBF3HZ3liBfK0q"),
        ("Şebnem Ferah - Sil Baştan", "https://open.spotify.com/track/1BAtLNflD3yp8PSrj8pTxX"),
        ("Fikri Karayel - Bir Şehri Sevmek", "https://open.spotify.com/track/0GqaQ8Vqk6fIYPZn1FeQac"),
        ("Feridun Düzağaç - Alev Alev", "https://open.spotify.com/track/6VAsXzYo8VLz4hnT6RgQdt")
    ],
    "nostaljik": [
        ("Barış Manço - Gülpembe", "https://open.spotify.com/track/0SVORe9xoyndIJoJbXj5eH"),
        ("MFÖ - Güllerin İçinden", "https://open.spotify.com/track/2Q5vCrLfNKFzCRXKUnGT8E"),
        ("Ajda Pekkan - Yan", "https://open.spotify.com/track/6yHtd6rEbIE5aVzWQCeJEn"),
        ("Sezen Aksu - Tükeneceğiz", "https://open.spotify.com/track/1zdiwPqNR6yCqRoUqXjISz"),
        ("Erol Evgin - Sevdan Olmasa", "https://open.spotify.com/track/3LRVvDE0vM3ZixM3I5FguE"),
        ("Nilüfer - Son Arzum", "https://open.spotify.com/track/3nWnt3DPAW7gclPi1mvExB"),
        ("Nazan Öncel - Sokak Kızı", "https://open.spotify.com/track/2xwhBdHZ6f9HEVNuYIfNMc"),
        ("Fikret Kızılok - Gönül", "https://open.spotify.com/track/2TZgQ5gJMLaaB6rJo7tEfB"),
        ("Yeni Türkü - Aşk Yeniden", "https://open.spotify.com/track/5rl2GoL7K7G7Zz5Sx14N7g"),
        ("Tanju Okan - Kadınım", "https://open.spotify.com/track/0Bg9kQ1uIv61vQqg3Ba93I"),
        ("Barış Manço - Kara Sevda ", "https://open.spotify.com/intl-tr/track/796lBatxeJCAWV83ZnWlJT?si=4887c290bcd548c5")
    ],
    "yorgun": [
        ("Cem Adrian - Hala Senin Suçun Var", "https://open.spotify.com/track/6Hw0UIEvAYPB67eQnJnpU1"),
        ("Pinhani - Beni Al", "https://open.spotify.com/track/6SnNKeTziOiY6wZgXqlzIG"),
        ("Mor ve Ötesi - Son Deneme", "https://open.spotify.com/track/2BJ9vOG6mE9iRE3YZ3tsnP"),
        ("Fikri Karayel - Hayal Edemezsin", "https://open.spotify.com/track/2nGLQ6Ry3qIGePYQzMiUO3"),
        ("Mabel Matiz - A Canım", "https://open.spotify.com/track/0oJY8cps2Z71N9w0yLmQgf"),
        ("Emre Aydın - Git", "https://open.spotify.com/track/0qFCBhExYlEXNDBgqAQ8Gq"),
        ("Bülent Ortaçgil - Bu Su Hiç Durmaz", "https://open.spotify.com/track/7K5B3Y9hf5bK1X0zLFR7a5"),
        ("Yaşar - On Bir Ay", "https://open.spotify.com/track/4gy6KCh2RL0KInbHqNcxUW"),
        ("Mavi Sakal - İki Yol", "https://open.spotify.com/track/5ziEvShygZmt5tYlXiHVzL"),
        ("Teoman - Gönülçelen", "https://open.spotify.com/track/7HGfgYmt3DZh09rQJkpEVA")
    ],
    "motive": [
        ("Sertab Erener - Kime Diyorum", "https://open.spotify.com/track/1xd9OiEBoSfrq8FbDRFSki"),
        ("Coolie - Gangsta's Paradise ", "https://open.spotify.com/intl-tr/track/1DIXPcTDzTj8ZMHt3PDt8p?si=545097458c2a478f"),
        ("Nil Karaibrahimgil - Kanatlarım Var Ruhumda", "https://open.spotify.com/track/0OVn3DfNgEJeZshXKoTck5"),
        ("Tarkan - Yolla", "https://open.spotify.com/track/0OzUuGQLhH7KmRsjvA3DyG"),
        ("Aleyna Tilki - Cevapsız Çınlama", "https://open.spotify.com/track/4vMOKX6jOAKuPGF4tpgjD4"),
        ("Kenan Doğulu - Aşk ile Yap", "https://open.spotify.com/track/1AQBtFZfmsvS0ZCIGynB9o"),
        ("Gökhan Türkmen - Çatı Katı", "https://open.spotify.com/track/1NW9Rhn9J7tGy0T1dDFEGP"),
        ("Edis - Arıyorum", "https://open.spotify.com/track/1FDGZchhDPTRf5JxFaZ3og"),
        ("Bora Duran - Sana Doğru", "https://open.spotify.com/track/6rcCyU1RoFapEnNgzpZDEg"),
        ("Sıla - Karanfil", "https://open.spotify.com/track/4fZbZ8gJKY9htI5xBdJgBa"),
        ("Göksel - Hayat Rüya Gibi", "https://open.spotify.com/track/7AgzrgUzBKxgyZnR15N3tG")
    ],
    "kaygılı": [
        ("Kalben - Yaralı", "https://open.spotify.com/track/0wU0rbi4xyQfTuxbCM3VO0"),
        ("Cem Adrian - Ben Sana Vurgunum", "https://open.spotify.com/track/0tZtdjcRhDsAxGbSE8hZsB"),
        ("Can Bonomo - Bardak Taştı", "https://open.spotify.com/track/6f6KhRl6rDQqBCiwMbnNXY"),
        ("Manuş Baba - Değmez", "https://open.spotify.com/track/63v4U9u6MXLZIjpluipKq6"),
        ("Teoman - O", "https://open.spotify.com/track/4tDkR2NpAtRuWSMEumr94j"),
        ("Pinhani - Ne Güzel Güldün", "https://open.spotify.com/track/3mKJfojqAmIHKg7WiLxKxa"),
        ("Melike Şahin - Uykumun Boynunu Bükme", "https://open.spotify.com/track/0Pst6mWMr1LxP5fQ5pJkaM"),
        ("Sıla - Ziyan", "https://open.spotify.com/track/0T7OuyY81hzmljDLKdkNsH"),
        ("Mor ve Ötesi - Ayıp Olmaz Mı?", "https://open.spotify.com/track/7exkqOmuYoM0aTyycPxCgD"),
        ("Fikri Karayel - Hayal Edemezsin", "https://open.spotify.com/track/2nGLQ6Ry3qIGePYQzMiUO3")
    ]
}
def spotify_embed(link):
    track_id = link.split("/")[-1].split("?")[0]
    return f"""
    <iframe style="border-radius:12px"
            src="https://open.spotify.com/embed/track/{track_id}"
            width="100%" height="80" frameBorder="0"
            allowtransparency="true" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"
            loading="lazy"></iframe>
    """

def dj_anonsu(selected_moods):
    # === DJ ANONSU ===
    prompt = "Ruh halim karmaşık ama derin. DJ gibi konuş:"
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    output = model.generate(**inputs, max_length=64, do_sample=True, top_p=0.85, temperature=0.7)
    model_cikisi = tokenizer.decode(output[0], skip_special_tokens=True)

    baslik = random.choice(basliklar)
    bitis = random.choice(bitisler)
    anons = f"{baslik} {model_cikisi} {bitis}"

    html_blok = ""
    renk_adi_listesi = []

    for mood in selected_moods:
        mod_giris = random.choice(mod_kaliplar)
        mood_upper = mood.upper()

        # ŞARKI
        if mood in sarki_veritabani and sarki_veritabani[mood]:
            sarki_adi, sarki_link = random.choice(sarki_veritabani[mood])
            sarki_html = f"<b>🎵 Şarkı:</b> {sarki_adi}<br>{spotify_embed(sarki_link)}"
        else:
            sarki_html = "<i>🎵 Bu duygu için şarkı bulunamadı.</i>"

        # RENK
        renk_adi, renk_hex = renk_ve_anlam.get(mood, ("beyaz", "#FFFFFF"))
        yazi_rengi = "black" if renk_hex.upper() == "#FFFFFF" else "white"
        renk_aciklama = renk_anlamlari.get(renk_adi, "Açıklama bulunamadı.")
        renk_adi_listesi.append(renk_adi.upper())

        renk_html = f"""
        <div style='width:100%; background-color:{renk_hex}; color:{yazi_rengi};
        text-align:center; border-radius:8px; font-weight:bold; padding:10px; margin-top:10px'>
            🧠 <i>{mod_giris} {mood_upper}.</i><br><br>
            {sarki_html}<br><br>
            🌈 <b>Renk:</b> {renk_adi.upper()} - {renk_aciklama}
        </div>
        """
        html_blok += renk_html + "<br>"

    # RENK ÖZETİ
    if len(renk_adi_listesi) > 1:
        html_blok += f"<br><b>🎨 Sen aslında bu renklerin bir karışımısın: {', '.join(renk_adi_listesi)}.</b>"
    elif len(renk_adi_listesi) == 1:
        html_blok += f"<br><b>🎨 Bugünkü ruhunun rengi: {renk_adi_listesi[0]}.</b>"
    else:
        html_blok += "<b>🎨 Ruh hali seçilmedi.</b>"

    return anons, html_blok

# === GRADIO ARAYÜZ ===
interface = gr.Interface(
    fn=dj_anonsu,
    inputs=gr.CheckboxGroup(duygu_etiketleri, label="🧠 Bugünkü ruh halini seç (birden fazla olabilir)"),
    outputs=[
        gr.Textbox(label="🎙️ DJ Anonsun"),
        gr.HTML(label="🎵+🎨 Şarkı & Tema Çıktısı")
    ],
    title="🎧 DJ Radyo",
    description="Ruh haline göre DJ tarzı konuşma, modunu anlatan şarkılar ve renk temaları al!"
)

interface.launch()

from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score, classification_report

# === ÖRNEK GERÇEK VE TAHMİN EDİLEN DUYGU ETİKETLERİ ===
gercek_etiketler = ["mutlu", "hüzünlü", "aşık", "enerjik", "yalnız"]
tahmin_edilenler = ["mutlu", "mutlu", "aşık", "enerjik", "yalnız"]

# === F1 Score ===
f1 = f1_score(gercek_etiketler, tahmin_edilenler, average='macro')  # equal weight to each class
print("F1 Score (macro):", round(f1, 3))

# === Doğruluk (Accuracy) ===
acc = accuracy_score(gercek_etiketler, tahmin_edilenler)
print("Accuracy:", round(acc, 3))

# === Precision ve Recall ===
precision = precision_score(gercek_etiketler, tahmin_edilenler, average='macro')
recall = recall_score(gercek_etiketler, tahmin_edilenler, average='macro')
print("Precision:", round(precision, 3))
print("Recall:", round(recall, 3))

# === Detaylı Rapor ===
print("\nSınıflandırma Raporu:\n")
print(classification_report(gercek_etiketler, tahmin_edilenler))