# -*- coding: utf-8 -*-
"""sarki_veritabani.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rVGcGz6YVueYncv-rYFqNSWSC3H9Fyb8
"""

sarki_veritabani = {

    "hüzünlü": [
        ("Ahmet Kaya - Kum Gibi", "https://open.spotify.com/track/5sNESr6pQfIhL3krM8CtZn"),
        ("Sezen Aksu - Gülümse", "https://open.spotify.com/track/3dWLnU94Yf5EX6w54N0vft"),
        ("Cem Adrian - Yalnızlık", "https://open.spotify.com/track/4uYzxd0W7UOHkMo7G5fK9o"),
        ("Manuş Baba - Eteği Belinde", "https://open.spotify.com/track/6Rwl8VWBYkcKU8aD0vWYRB"),
        ("Teoman - Kupa Kızı ve Sinek Valesi", "https://open.spotify.com/track/7s5L2HQI9iYjA2Jssm9Rre"),
        ("Feridun Düzağaç - Lavinya", "https://open.spotify.com/track/0XpdGFGcV48qN3oUNrWiTT"),
        ("Fikri Karayel - Yol", "https://open.spotify.com/track/0NaidDHuhrUlaKFLfp0XUi"),
        ("Melike Şahin - Sevmek Suçsa Suçluyum", "https://open.spotify.com/track/0BAI3tbiBNu8ZQZUZhfw7A"),
        ("Mabel Matiz - A Canım", "https://open.spotify.com/track/0oJY8cps2Z71N9w0yLmQgf"),
        ("Gripin - Durma Yağmur Durma", "https://open.spotify.com/track/4q3U8Mum6wl1Z2VjXivvTk")
    ],
    "mutlu": [
        ("Tarkan - Şımarık", "https://open.spotify.com/track/2WzWqVs2Yh0ZTfPikYpWIZ"),
        ("Kenan Doğulu - Çakkıdı", "https://open.spotify.com/track/1o5RtFKEJH1tU3cyZKXjCx"),
        ("Nil Karaibrahimgil - Ben Buraya Çıplak Geldim", "https://open.spotify.com/track/0cHRN4O1s3mt0IOLiTJpG0"),
        ("Athena - Arsız Gönül", "https://open.spotify.com/track/7IP5Fq3F09iLgCP6reUrVR"),
        ("MFÖ - Ele Güne Karşı", "https://open.spotify.com/track/0smAAirKoLoehnVYBo2L7m"),
        ("Kiss - I Was Made For Lovin' You ", "https://open.spotify.com/intl-tr/track/07q0QVgO56EorrSGHC48y3?si=f65426af566547a5"),
        ("Mor ve Ötesi - Bir Derdim Var", "https://open.spotify.com/track/6IdCHwfh5kbE3cKmFqCSx5"),
        ("Hande Yener - Kırmızı", "https://open.spotify.com/track/6RX5iFmyQjRpgO1xGJ5L9T"),
        ("Ajda Pekkan - Yakar Geçerim", "https://open.spotify.com/track/4vq2SvLKHHM1bCNiTf9yFr"),
        ("Göksel - Depresyondayım", "https://open.spotify.com/track/4NHmNIFezcyV7nFeKZCMRH"),
        ("Athena - Senden, Benden, Bizden", "https://open.spotify.com/track/2pYHyEVRuMdn4ImLaBPKY5")
    ],
    "aşık": [
        ("Yalın - Bir Bakmışsın", "https://open.spotify.com/track/5a9bV2xC6Ab7Rk8NV7OfIP"),
        ("Emre Aydın - Belki Bir Gün Özlersin", "https://open.spotify.com/track/3uA5LnZ4nLwF2rVRUMi30a"),
        ("Tuna Kiremitçi - Bu Aşk Burada Biter", "https://open.spotify.com/track/0Zq04yAFYJr7rkOhmDZKDr"),
        ("Kalben - Sadece", "https://open.spotify.com/track/4Z9Drs6dp0QF1G13wLChPw"),
        ("Mabel Matiz - Gök Nerede", "https://open.spotify.com/track/6NnOgo2vNnMk8cJmo7r3Mw"),
        ("Edis - Martılar", "https://open.spotify.com/track/63g9ucLfjz2YKMzpxLysJ9"),
        ("Sıla - Yan Benimle", "https://open.spotify.com/track/4NVoaVJoPZo3JOGK9VmYnc"),
        ("Nilüfer - Son Perde", "https://open.spotify.com/track/0B1LFqOn2bbAOKWYIoFHZj"),
        ("Fenerbahçeliler - Lacivert Olmadan Sarı Sevilmez ", "https://open.spotify.com/intl-tr/track/5m0XSgInSBejkOyO4Fk59u?si=cc2e2dd6d7f54686"),
        ("Sertab Erener - Açık Adres", "https://open.spotify.com/track/0dL2BDkxl5z6zM6tMKLbDr"),
        ("Duman - Elleri Ellerime", "https://open.spotify.com/track/4u6EQz7w5CWwbHu4rhIuXy")
    ],
    "sinirli": [
        ("maNga - Beni Benimle Bırak", "https://open.spotify.com/track/5jyiF1DeNVzP5PBcLMxyZ2"),
        ("Mor ve Ötesi - Cambaz", "https://open.spotify.com/track/7pTnXzy3zzmtBOOvIczm4d"),
        ("Hayko Cepkin - Melekler", "https://open.spotify.com/track/1CCayHgCFFxPBwGzltChfG"),
        ("Duman - Belki Alışman Lazım", "https://open.spotify.com/track/4U3A7PQbx1qR5uNHQJsb2T"),
        ("Athena - Serseri Mayın", "https://open.spotify.com/track/0ObQ2dMw1yizn45RlGZKj3"),
        ("Şebnem Ferah - Mayın Tarlası", "https://open.spotify.com/track/4vAaQww8xMDn2mEZU7o1e6"),
        ("Kurban - Yosma", "https://open.spotify.com/track/3NKJjRYGLmNkoUZVnpR1wb"),
        ("Pentagram - Lions In A Cage", "https://open.spotify.com/track/2HTEjrPBHhzRMz8l4TBAg7"),
        ("Redd - Nefes Bile Almadan", "https://open.spotify.com/track/3D5LqZYptmFVW0Qd7xwbgN"),
        ("Cem Adrian - Sen Gel Diyorsun", "https://open.spotify.com/track/0GT0D54Ndiwwj0gEBE1a5Y")
    ],
    "enerjik": [
        ("Hadise - Düm Tek Tek", "https://open.spotify.com/track/3CJ74wGJb1ErfhCe9xH1kM"),
        ("Tarkan - Kuzu Kuzu", "https://open.spotify.com/track/4S7hnAp0uohRSMd4TrbSFL"),
        ("Gülşen - Bangır Bangır", "https://open.spotify.com/track/6zbmY9UKiWHD91aPPvp9hz"),
        ("Aleyna Tilki - Sen Olsan Bari", "https://open.spotify.com/track/0M2JbYkZB5WrrvhzraO5cT"),
        ("Edis - Dudak", "https://open.spotify.com/track/4C0WRYvciVXN7oL6gDJswV"),
        ("Demet Akalın - Nazar", "https://open.spotify.com/track/4gbRWljOtDLZOVWJk1K3Yo"),
        ("Simge - Yankı", "https://open.spotify.com/track/1rVcdVxapxOhyDf7S7phb2"),
        ("Ziynet Sali - Bana da Söyle", "https://open.spotify.com/track/1ugA1nP39TiMnTTe64N7NY"),
        ("Ajda Pekkan - Ajda 1990", "https://open.spotify.com/track/5oLKMnpyXjJvOE1phGMZCz"),
        ("Sertab Erener - Rengarenk", "https://open.spotify.com/track/6NkxOSSh7nRlyDdVcz0b96"),
        ("Yaşar - Kumralım", "https://open.spotify.com/intl-tr/track/3tCCD2qQLdC99YkRwGPSsx?si=dedf8318d62a4ddf")
    ],
    "yalnız": [
        ("Cem Adrian - Yalnızlık Senden Daha Çok Seviyor Beni", "https://open.spotify.com/track/6pPhQ6AStRt8s2VG0imU2F"),
        ("Manuş Baba - Ben Sana Vurgunum", "https://open.spotify.com/track/2XvHyqMkhqvJzjU4Ox5D7E"),
        ("Gripin - Yalnızlığın Çaresini Bulmuşlar", "https://open.spotify.com/track/6rIu5MbOeaqgWMSbXHE1x6"),
        ("Teoman - Renkli Rü yalar Oteli", "https://open.spotify.com/track/2S9lOTUUfNRnBeB0Te6rxg"),
        ("Berkay - Ayrılmam", "https://open.spotify.com/track/7rA6vIE9XWbyV6tk3MRVTh"),
        ("Kalben - Sadece", "https://open.spotify.com/track/4Z9Drs6dp0QF1G13wLChPw"),
        ("Candan Erçetin - Yalan", "https://open.spotify.com/track/4VjBd2HodBF3HZ3liBfK0q"),
        ("Şebnem Ferah - Sil Baştan", "https://open.spotify.com/track/1BAtLNflD3yp8PSrj8pTxX"),
        ("Fikri Karayel - Bir Şehri Sevmek", "https://open.spotify.com/track/0GqaQ8Vqk6fIYPZn1FeQac"),
        ("Feridun Düzağaç - Alev Alev", "https://open.spotify.com/track/6VAsXzYo8VLz4hnT6RgQdt")
    ],
    "nostaljik": [
        ("Barış Manço - Gülpembe", "https://open.spotify.com/track/0SVORe9xoyndIJoJbXj5eH"),
        ("MFÖ - Güllerin İçinden", "https://open.spotify.com/track/2Q5vCrLfNKFzCRXKUnGT8E"),
        ("Ajda Pekkan - Yan", "https://open.spotify.com/track/6yHtd6rEbIE5aVzWQCeJEn"),
        ("Sezen Aksu - Tükeneceğiz", "https://open.spotify.com/track/1zdiwPqNR6yCqRoUqXjISz"),
        ("Erol Evgin - Sevdan Olmasa", "https://open.spotify.com/track/3LRVvDE0vM3ZixM3I5FguE"),
        ("Nilüfer - Son Arzum", "https://open.spotify.com/track/3nWnt3DPAW7gclPi1mvExB"),
        ("Nazan Öncel - Sokak Kızı", "https://open.spotify.com/track/2xwhBdHZ6f9HEVNuYIfNMc"),
        ("Fikret Kızılok - Gönül", "https://open.spotify.com/track/2TZgQ5gJMLaaB6rJo7tEfB"),
        ("Yeni Türkü - Aşk Yeniden", "https://open.spotify.com/track/5rl2GoL7K7G7Zz5Sx14N7g"),
        ("Tanju Okan - Kadınım", "https://open.spotify.com/track/0Bg9kQ1uIv61vQqg3Ba93I"),
        ("Barış Manço - Kara Sevda ", "https://open.spotify.com/intl-tr/track/796lBatxeJCAWV83ZnWlJT?si=4887c290bcd548c5")
    ],
    "yorgun": [
        ("Cem Adrian - Hala Senin Suçun Var", "https://open.spotify.com/track/6Hw0UIEvAYPB67eQnJnpU1"),
        ("Pinhani - Beni Al", "https://open.spotify.com/track/6SnNKeTziOiY6wZgXqlzIG"),
        ("Mor ve Ötesi - Son Deneme", "https://open.spotify.com/track/2BJ9vOG6mE9iRE3YZ3tsnP"),
        ("Fikri Karayel - Hayal Edemezsin", "https://open.spotify.com/track/2nGLQ6Ry3qIGePYQzMiUO3"),
        ("Mabel Matiz - A Canım", "https://open.spotify.com/track/0oJY8cps2Z71N9w0yLmQgf"),
        ("Emre Aydın - Git", "https://open.spotify.com/track/0qFCBhExYlEXNDBgqAQ8Gq"),
        ("Bülent Ortaçgil - Bu Su Hiç Durmaz", "https://open.spotify.com/track/7K5B3Y9hf5bK1X0zLFR7a5"),
        ("Yaşar - On Bir Ay", "https://open.spotify.com/track/4gy6KCh2RL0KInbHqNcxUW"),
        ("Mavi Sakal - İki Yol", "https://open.spotify.com/track/5ziEvShygZmt5tYlXiHVzL"),
        ("Teoman - Gönülçelen", "https://open.spotify.com/track/7HGfgYmt3DZh09rQJkpEVA")
    ],
    "motive": [
        ("Sertab Erener - Kime Diyorum", "https://open.spotify.com/track/1xd9OiEBoSfrq8FbDRFSki"),
        ("Coolie - Gangsta's Paradise ", "https://open.spotify.com/intl-tr/track/1DIXPcTDzTj8ZMHt3PDt8p?si=545097458c2a478f"),
        ("Nil Karaibrahimgil - Kanatlarım Var Ruhumda", "https://open.spotify.com/track/0OVn3DfNgEJeZshXKoTck5"),
        ("Tarkan - Yolla", "https://open.spotify.com/track/0OzUuGQLhH7KmRsjvA3DyG"),
        ("Aleyna Tilki - Cevapsız Çınlama", "https://open.spotify.com/track/4vMOKX6jOAKuPGF4tpgjD4"),
        ("Kenan Doğulu - Aşk ile Yap", "https://open.spotify.com/track/1AQBtFZfmsvS0ZCIGynB9o"),
        ("Gökhan Türkmen - Çatı Katı", "https://open.spotify.com/track/1NW9Rhn9J7tGy0T1dDFEGP"),
        ("Edis - Arıyorum", "https://open.spotify.com/track/1FDGZchhDPTRf5JxFaZ3og"),
        ("Bora Duran - Sana Doğru", "https://open.spotify.com/track/6rcCyU1RoFapEnNgzpZDEg"),
        ("Sıla - Karanfil", "https://open.spotify.com/track/4fZbZ8gJKY9htI5xBdJgBa"),
        ("Göksel - Hayat Rüya Gibi", "https://open.spotify.com/track/7AgzrgUzBKxgyZnR15N3tG")
    ],
    "kaygılı": [
        ("Kalben - Yaralı", "https://open.spotify.com/track/0wU0rbi4xyQfTuxbCM3VO0"),
        ("Cem Adrian - Ben Sana Vurgunum", "https://open.spotify.com/track/0tZtdjcRhDsAxGbSE8hZsB"),
        ("Can Bonomo - Bardak Taştı", "https://open.spotify.com/track/6f6KhRl6rDQqBCiwMbnNXY"),
        ("Manuş Baba - Değmez", "https://open.spotify.com/track/63v4U9u6MXLZIjpluipKq6"),
        ("Teoman - O", "https://open.spotify.com/track/4tDkR2NpAtRuWSMEumr94j"),
        ("Pinhani - Ne Güzel Güldün", "https://open.spotify.com/track/3mKJfojqAmIHKg7WiLxKxa"),
        ("Melike Şahin - Uykumun Boynunu Bükme", "https://open.spotify.com/track/0Pst6mWMr1LxP5fQ5pJkaM"),
        ("Sıla - Ziyan", "https://open.spotify.com/track/0T7OuyY81hzmljDLKdkNsH"),
        ("Mor ve Ötesi - Ayıp Olmaz Mı?", "https://open.spotify.com/track/7exkqOmuYoM0aTyycPxCgD"),
        ("Fikri Karayel - Hayal Edemezsin", "https://open.spotify.com/track/2nGLQ6Ry3qIGePYQzMiUO3")
    ]
}